export const quastions = [
    // {ask: `Who played the main role in the movie "Inception"?`,
    // answer: `Leonardo DiCaprio`},
    // {ask: `Who is the director of the Star Wars movie?`,
    // answer: `George Lucas`},
    // {ask: `Continue the legendary phrase “Luke, …”`,
    // answer: `I am your father`},
    // {ask: `Who played Harry Potter in the movie?`,
    // answer: `Daniel Radcliffe`},
    // {ask: `What were the names of the two main villains in Home Alone?`,
    // answer: `Harry and  Marvin`},
    // {ask: `What were the names of Harry Potter's parents?`,
    // answer: `Lily and James`},
    // {ask: `What is the name of the main character of the movie: Pirates of the Caribbean?`,
    // answer: `Captain Jack Sparrow`},
    // {ask: `The name of the series is ".... of thrones"`,
    // answer: `Game`},
    // {ask: `What is the last name of the protagonist of Fast & Furious: Dominic...?`,
    // answer: `Toretto`},
    // {ask: ` Who was Frodo Baggins?`,
    // answer: `hobbit`},
    {ask: `Harry Potter Friend: ...Weasley?`,
    answer: `Ron`},
    // {ask: `Thor's weapon?`,
    // answer: `Hummer`},
    // {ask: `The first Avenger?`,
    // answer: `Captain America`},
    // {ask: `Who was the director of the film "The Fifth Element"?`,
    // answer: `Luc Besson`},
    // {ask: `Who was fed by grandma in the park in the movie "Home Alone"?`,
    // answer: `pigeons`},
    // {ask: `Continue the title of the movie with Bruce Willis: "Sixth..."`,
    // answer: `Sense`},
    // {ask: `The name of the main character in the movie "Pretty Woman"`,
    // answer: `Edward`},
    // {ask: `Continue the title of the movie with Tom Cruise: "Mission ...`,
    // answer: `Impossible`},
]

